<?php

namespace App\Helper;


class TypeAction
{
    const NEW_ORDER = "NEW_ORDER"; //Đơn hàng mới
    const NEW_POST = "NEW_POST"; //Bai viet mới
    const SEND_ALL = "SEND_ALL";
    const ORDER_STATUS = "ORDER_STATUS"; //Bai viet mới
    const NEW_MESSAGE = "NEW_MESSAGE"; //Tin nhắn mới
    const CUSTOMER_CANCELLED_ORDER = "CUSTOMER_CANCELLED_ORDER"; //Khách đã hủy đơn hàng
    const CUSTOMER_PAID = "CUSTOMER_PAID"; //Khách đã thanh toán
    const TO_ADMIN = "TO_ADMIN"; //gửi đến admin


    const OPERATION_ACTION_ADD = "OPERATION_ACTION_ADD";
    const OPERATION_ACTION_DELETE = "OPERATION_ACTION_DELETE";
    const OPERATION_ACTION_UPDATE = "OPERATION_ACTION_UPDATE";
    const OPERATION_ACTION_CANCEL = "OPERATION_ACTION_CANCEL";

    const FUNCTION_TYPE_PRODUCT = "FUNCTION_TYPE_PRODUCT";
    const FUNCTION_TYPE_INVENTORY = "FUNCTION_TYPE_INVENTORY";
    const FUNCTION_TYPE_CATEGORY_PRODUCT = "FUNCTION_TYPE_CATEGORY_PRODUCT";
    const FUNCTION_TYPE_CATEGORY_POST = "FUNCTION_TYPE_CATEGORY_POST";
    const FUNCTION_TYPE_ORDER = "FUNCTION_TYPE_ORDER";
    const FUNCTION_TYPE_THEME = "FUNCTION_TYPE_THEME";
    const FUNCTION_TYPE_PROMOTION = "FUNCTION_TYPE_PROMOTION";
    const FUNCTION_POINT = "FUNCTION_POINT";
}
