<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Base\BaseModel;

class Decentralization extends BaseModel
{
    use HasFactory;
    protected $guarded = [];

    protected $casts = [
        "product_list" => 'boolean',
        "product_add" => 'boolean',
        "product_update" => 'boolean',
        "product_copy" => 'boolean',
        "product_remove_hide" => 'boolean',
        "product_category_list" => 'boolean',
        "product_category_add" => 'boolean',
        "product_category_update" => 'boolean',
        "product_category_remove" => 'boolean',
        "product_attribute_list" => 'boolean',
        "product_attribute_add" => 'boolean',
        "product_attribute_update" => 'boolean',
        "product_attribute_remove" => 'boolean',
        "product_ecommerce" => 'boolean',
        "product_import_from_excel" => 'boolean',
        "product_export_to_excel" => 'boolean',
        "customer_list" => 'boolean',
        "customer_list_export" => 'boolean',
        "customer_list_import" => 'boolean',
        "customer_config_point" => 'boolean',
        "customer_review_list" => 'boolean',
        "customer_review_censorship" => 'boolean',
        "customer_role_edit" => 'boolean',
        "customer_change_point" => 'boolean',
        "customer_change_referral" => 'boolean',
        "promotion_discount_list" => 'boolean',
        "promotion_discount_add" => 'boolean',
        "promotion_discount_update" => 'boolean',
        "promotion_discount_end" => 'boolean',
        "promotion_voucher_list" => 'boolean',
        "promotion_voucher_add" => 'boolean',
        "promotion_voucher_update" => 'boolean',
        "promotion_voucher_end" => 'boolean',
        "promotion_combo_list" => 'boolean',
        "promotion_combo_add" => 'boolean',
        "promotion_combo_update" => 'boolean',
        "promotion_combo_end" => 'boolean',
        "collaborator_add_sub_balance" => 'boolean',
        "agency_config" => 'boolean',
        "agency_payment_request_list" => 'boolean',
        "agency_payment_request_solve" => 'boolean',
        "agency_payment_request_history" => 'boolean',
        "agency_add_sub_balance" => 'boolean',
        "order_list" => 'boolean',
        "order_allow_change_status" => 'boolean',
        "post_list" => 'boolean',
        "post_add" => 'boolean',
        "post_update" => 'boolean',
        "post_remove_hide" => 'boolean',
        "post_category_list" => 'boolean',
        "post_category_add" => 'boolean',
        "post_category_update" => 'boolean',
        "post_category_remove" => 'boolean',
        "app_theme_edit" => 'boolean',
        "app_theme_main_config" => 'boolean',
        "app_theme_button_contact" => 'boolean',
        "app_theme_home_screen" => 'boolean',
        "app_theme_main_component" => 'boolean',
        "app_theme_category_product" => 'boolean',
        "app_theme_product_screen" => 'boolean',
        "app_theme_contact_screen" => 'boolean',
        "web_theme_edit" => 'boolean',
        "web_theme_overview" => 'boolean',
        "web_theme_contact" => 'boolean',
        "web_theme_help" => 'boolean',
        "web_theme_footer" => 'boolean',
        "web_theme_banner" => 'boolean',
        "web_theme_seo" => 'boolean',
        "delivery_pick_address_list" => 'boolean',
        "delivery_pick_address_update" => 'boolean',
        "delivery_provider_update" => 'boolean',
        "payment_list" => 'boolean',
        "payment_on_off" => 'boolean',
        "notification_schedule_list" => 'boolean',
        "notification_schedule_add" => 'boolean',
        "notification_schedule_remove_pause" => 'boolean',
        "notification_schedule_update" => 'boolean',
        "popup_list" => 'boolean',
        "popup_add" => 'boolean',
        "popup_update" => 'boolean',
        "popup_remove" => 'boolean',
        "collaborator_config" => 'boolean',
        "collaborator_list" => 'boolean',
        "collaborator_view" => 'boolean',
        "collaborator_payment_request_list" => 'boolean',
        "collaborator_payment_request_solve" => 'boolean',
        "collaborator_payment_request_history" => 'boolean',
        "notification_to_stote" => 'boolean',
        "agency_list" => 'boolean',
        "agency_view" => 'boolean',
        "agency_change_level" => 'boolean',
        "chat_list" => 'boolean',
        "chat_allow" => 'boolean',
        "report_view" => 'boolean',
        "report_overview" => 'boolean',
        "report_product" => 'boolean',
        "report_order" => 'boolean',
        "decentralization_list" => 'boolean',
        "decentralization_update" => 'boolean',
        "decentralization_add" => 'boolean',
        "decentralization_remove" => 'boolean',
        "staff_list" => 'boolean',
        "staff_update" => 'boolean',
        "staff_add" => 'boolean',
        "staff_remove" => 'boolean',
        "staff_delegating" => 'boolean',

        "inventory_list" => 'boolean',
        "inventory_import" => 'boolean',
        "inventory_tally_sheet" => 'boolean',

        "revenue_expenditure" => 'boolean',

        "promotion" => 'boolean',
        "report_inventory" => 'boolean',
        "report_finance" => 'boolean',
        "add_revenue" => 'boolean',
        "add_expenditure" => 'boolean',
        "setting_print" => 'boolean',
        "store_info" => 'boolean',
        "branch_list" => 'boolean',
        "config_setting" => 'boolean',
        "config_terms_agency_collaborator" => 'boolean',

        "create_order_pos" => 'boolean',
        "change_price_pos" => 'boolean',
        "change_discount_pos" => 'boolean',
        "supplier" => 'boolean',
        "barcode_print" => 'boolean',
        "timekeeping" => 'boolean',
        "transfer_stock" => 'boolean',
        "onsale" => 'boolean',
        "train" => 'boolean',
        "train_add" => 'boolean',
        "train_update" => 'boolean',
        "train_delete" => 'boolean',
        "train_exam_list" => 'boolean',
        "train_exam_add" => 'boolean',
        "train_exam_update" => 'boolean',
        "train_exam_delete" => 'boolean',
        "train_exam_history" => 'boolean',

        "overview" => 'boolean',
        "vip_edit" => 'boolean',
        "onsale_edit" => 'boolean',
        "onsale_add" => 'boolean',
        "onsale_remove" => 'boolean',
        "onsale_assignment" => 'boolean',

        "gamification" => 'boolean',
        "sale_list" => 'boolean',
        "sale_view" => 'boolean',

        "ecommerce_list" => 'boolean',
        "ecommerce_products" => 'boolean',
        "ecommerce_connect" => 'boolean',
        "ecommerce_orders" => 'boolean',
        "ecommerce_inventory" => 'boolean',

        "config_sms" => 'boolean',
        "accountant_time_sheet" => 'boolean',
        "agency_bonus_program" => 'boolean',
        "agency_register" => 'boolean',
        "agency_top_commission" => 'boolean',
        "agency_top_import" => 'boolean',
        "banner_ads" => 'boolean',
        "collaborator_register" => 'boolean',
        "collaborator_top_sale" => 'boolean',
        "invoice_template" => 'boolean',
        "onsale_list" => 'boolean',
        "order_export_to_excel" => 'boolean',
        "order_import_from_excel" => 'boolean',
        "product_commission" => 'boolean',
        "product_export_to_excel" => 'boolean',
        "product_import_from_excel" => 'boolean',
        "promotion_bonus_product_add" => 'boolean',
        "promotion_bonus_product_end" => 'boolean',
        "promotion_bonus_product_update" => 'boolean',
        "promotion_bonus_product_list" => 'boolean',
        "sale_config" => 'boolean',
        "sale_top" => 'boolean',
        "group_customer" => 'boolean',
        "history_operation" => 'boolean',
        "sale_watching" => 'boolean',
        "communication_list" => 'boolean',
        "communication_update" => 'boolean',
        "communication_delete" => 'boolean',
        "communication_add" => 'boolean',
        "communication_approve" => 'boolean',
    ];
}
